//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJohnnatan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TAdministrator
    {
        public int AdministratorId { get; set; }

        [Display(Name = "User")]
        [Required(ErrorMessage = "This field is Required")]
        public string AdministratorUser { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "This field is Required")]
        [DataType(DataType.Password)]
        public string AdministratorPassword { get; set; }

        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage = "This field is Required")]
        [DataType(DataType.Password)]
        [Compare("AdministratorPassword")]
        public string ConfirmPassword { get; set; }

        public string MessageLoginError { get; set; }
    }
}
