//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJohnnatan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TModel
    {
        [Display(Name = "Model Id")]
        public int ModelId { get; set; }

        [Display(Name = "Model Name")]
        [Required]
        public string ModelName { get; set; }

        [Display(Name = "Brand Id")]
        public int BrandId { get; set; }
    
        public virtual TBrand TBrand { get; set; }

        [NotMapped]
        [Display(Name = "Brand Name")]
        public string BrandName { get; set; }

        [NotMapped]
        public List<TBrand> ListOfBrands { get; set; }

        [NotMapped]
        public List<TModel> ListOfModels { get; set; }
    }
}
