//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectJohnnatan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TUser
    {
        public int UserId { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "This field is Required")]
        [EmailAddress]
        public string UserEmail { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "This field is Required")]
        [DataType(DataType.Password)]
        public string UserPassword { get; set; }

        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage = "This field is Required")]
        [DataType(DataType.Password)]
        [Compare("UserPassword")]
        public string ConfirmPassword { get; set; }

        public string MessageLoginError { get; set; }

        public virtual TBrand TBrand { get; set; }

        [NotMapped]
        [Display(Name = "Brand Id")]
        public int BrandId { get; set; }

        [NotMapped]
        [Display(Name = "Brand Name")]
        public string BrandName { get; set; }

        [NotMapped]
        public List<TBrand> ListOfBrands { get; set; }

        public virtual TModel TModel { get; set; }

        [NotMapped]
        [Display(Name = "Model Id")]
        public int ModelId { get; set; }

        [NotMapped]
        [Display(Name = "Model Name")]
        public string ModelName { get; set; }

        [NotMapped]
        public List<TModel> ListOfModels { get; set; }

        [NotMapped]
        [Range(1, 100)]
        [DataType(DataType.Currency)]
        [Required(ErrorMessage = "This field is Required")]
        public int Price { get; set; }
    }
}
